name: quality-gates
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ qg/quality-gates ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install tools
        run: |
          pip install codespell
          pip install lychee-link-checker
          npm i -g markdownlint-cli@0.41.0 @mermaid-js/mermaid-cli@10.9.1
          pip install yamllint
          pip install pre-commit
      - name: Pre-commit
        run: |
          pre-commit run --all-files
      - name: Link check (lychee)
        run: |
          lychee --config lychee.toml --accept 200-299,403 --verbose . || (echo "Lychee found issues" && exit 1)
      - name: Mermaid render check
        run: |
          bash scripts/check_mermaid.sh
      - name: EN–ZH sync check
        run: |
          python scripts/check_sync.py
